// <auto-generated />
using System;
using APIRestCOURS.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIRestCOURS.DataAccess.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20251110085151_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("APIRestCOURS.DataAccess.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 50000.00m,
                            Iban = "FR7612345678901234567890123",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Balance = 25000.00m,
                            Iban = "FR7612345678901234567890124",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 3,
                            Balance = 120000.00m,
                            Iban = "FR7698765432109876543210987",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 4,
                            Balance = 85000.00m,
                            Iban = "FR7611111111111111111111111",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 5,
                            Balance = 200000.00m,
                            Iban = "FR7622222222222222222222222",
                            OwnerId = 4
                        });
                });

            modelBuilder.Entity("APIRestCOURS.DataAccess.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("APIRestCOURS.DataAccess.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Amount = 10000.00m,
                            At = new DateTime(2024, 10, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 0
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 1,
                            Amount = 2500.00m,
                            At = new DateTime(2024, 10, 16, 14, 30, 0, 0, DateTimeKind.Utc),
                            Kind = 1
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 1,
                            Amount = 5000.00m,
                            At = new DateTime(2024, 10, 21, 9, 15, 0, 0, DateTimeKind.Utc),
                            Kind = 0
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 2,
                            Amount = 15000.00m,
                            At = new DateTime(2024, 10, 26, 11, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 0
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 2,
                            Amount = 3000.00m,
                            At = new DateTime(2024, 10, 31, 16, 45, 0, 0, DateTimeKind.Utc),
                            Kind = 1
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 3,
                            Amount = 50000.00m,
                            At = new DateTime(2024, 10, 13, 10, 30, 0, 0, DateTimeKind.Utc),
                            Kind = 0
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 3,
                            Amount = 8000.00m,
                            At = new DateTime(2024, 10, 23, 13, 20, 0, 0, DateTimeKind.Utc),
                            Kind = 1
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 3,
                            Amount = 12000.00m,
                            At = new DateTime(2024, 11, 5, 15, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 1
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 4,
                            Amount = 30000.00m,
                            At = new DateTime(2024, 10, 19, 12, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 0
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 4,
                            Amount = 5000.00m,
                            At = new DateTime(2024, 10, 29, 17, 30, 0, 0, DateTimeKind.Utc),
                            Kind = 1
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 5,
                            Amount = 100000.00m,
                            At = new DateTime(2024, 10, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 0
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 5,
                            Amount = 25000.00m,
                            At = new DateTime(2024, 11, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            Kind = 1
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 5,
                            Amount = 15000.00m,
                            At = new DateTime(2024, 11, 7, 11, 30, 0, 0, DateTimeKind.Utc),
                            Kind = 0
                        });
                });

            modelBuilder.Entity("APIRestCOURS.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateNaissance = new DateTime(1990, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jean.dupont@email.com",
                            Nom = "Dupont",
                            PasswordHash = "oQnjaUetVt4dyhzEnw74rJrZp7GqDfQfs8TLc8H/Aeo=",
                            Prenom = "Jean"
                        },
                        new
                        {
                            Id = 2,
                            DateNaissance = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marie.martin@email.com",
                            Nom = "Martin",
                            PasswordHash = "oQnjaUetVt4dyhzEnw74rJrZp7GqDfQfs8TLc8H/Aeo=",
                            Prenom = "Marie"
                        },
                        new
                        {
                            Id = 3,
                            DateNaissance = new DateTime(1995, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pierre.durand@email.com",
                            Nom = "Durand",
                            PasswordHash = "oQnjaUetVt4dyhzEnw74rJrZp7GqDfQfs8TLc8H/Aeo=",
                            Prenom = "Pierre"
                        },
                        new
                        {
                            Id = 4,
                            DateNaissance = new DateTime(1988, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sophie.bernard@email.com",
                            Nom = "Bernard",
                            PasswordHash = "oQnjaUetVt4dyhzEnw74rJrZp7GqDfQfs8TLc8H/Aeo=",
                            Prenom = "Sophie"
                        });
                });

            modelBuilder.Entity("APIRestCOURS.DataAccess.Models.Account", b =>
                {
                    b.HasOne("APIRestCOURS.DataAccess.Models.User", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("APIRestCOURS.DataAccess.Models.RefreshToken", b =>
                {
                    b.HasOne("APIRestCOURS.DataAccess.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIRestCOURS.DataAccess.Models.Transaction", b =>
                {
                    b.HasOne("APIRestCOURS.DataAccess.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("APIRestCOURS.DataAccess.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("APIRestCOURS.DataAccess.Models.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
